create or replace function public.taleforge_verify_chapter_planning()
returns jsonb language plpgsql security definer set search_path=public
as $$
declare production_series integer; covered_series integer; uncovered_series integer; duplicate_chapter_versions integer; invalid_blueprints integer; noncontiguous_series integer; orphan_blueprints integer; result jsonb;
begin
select count(*) into production_series from public.series s where not (coalesce(s.description,'') ilike '%temporary internal series%' or coalesce(s.ai_disclosure,'') ilike '%internal test content%');
select count(distinct cb.series_id) into covered_series from public.chapter_blueprints cb join public.series s on s.id=cb.series_id where cb.generation_status in ('planned','queued','generating','generated','published') and not (coalesce(s.description,'') ilike '%temporary internal series%' or coalesce(s.ai_disclosure,'') ilike '%internal test content%');
select count(*) into duplicate_chapter_versions from (select series_id,chapter_number,version from public.chapter_blueprints where generation_status in ('planned','queued','generating','generated','published') group by series_id,chapter_number,version having count(*)>1) d;
select count(*) into invalid_blueprints from public.chapter_blueprints cb join public.series s on s.id=cb.series_id where cb.generation_status in ('planned','queued','generating','generated','published') and not (coalesce(s.description,'') ilike '%temporary internal series%' or coalesce(s.ai_disclosure,'') ilike '%internal test content%') and (cb.chapter_number<1 or cb.version<1 or coalesce(btrim(cb.purpose),'')='' or coalesce(btrim(cb.summary),'')='' or jsonb_typeof(coalesce(cb.plot_events,'null'::jsonb))<>'array' or jsonb_typeof(coalesce(cb.character_developments,'null'::jsonb))<>'array' or jsonb_typeof(coalesce(cb.world_reveals,'null'::jsonb))<>'array' or jsonb_typeof(coalesce(cb.clues_and_mysteries,'null'::jsonb))<>'array' or jsonb_typeof(coalesce(cb.continuity_requirements,'null'::jsonb))<>'array' or jsonb_typeof(coalesce(cb.previous_chapter_dependencies,'null'::jsonb))<>'array' or coalesce(btrim(cb.ending_hook),'')='' or cb.target_word_count<500 or cb.generation_status not in ('planned','queued','generating','generated','published') or cb.release_status not in ('unreleased','scheduled','released'));
select count(*) into noncontiguous_series from (select s.id from public.series s where not (coalesce(s.description,'') ilike '%temporary internal series%' or coalesce(s.ai_disclosure,'') ilike '%internal test content%') and exists(select 1 from public.chapter_blueprints cb where cb.series_id=s.id and cb.generation_status in ('planned','queued','generating','generated','published')) and ((select min(cb.chapter_number) from public.chapter_blueprints cb where cb.series_id=s.id and cb.generation_status in ('planned','queued','generating','generated','published'))<>1 or (select count(distinct cb.chapter_number) from public.chapter_blueprints cb where cb.series_id=s.id and cb.generation_status in ('planned','queued','generating','generated','published'))<>((select max(cb.chapter_number) from public.chapter_blueprints cb where cb.series_id=s.id and cb.generation_status in ('planned','queued','generating','generated','published'))))) x;
select count(*) into orphan_blueprints from public.chapter_blueprints cb left join public.series s on s.id=cb.series_id where s.id is null;
uncovered_series:=production_series-covered_series;
result:=jsonb_build_object('status',case when uncovered_series=0 and duplicate_chapter_versions=0 and invalid_blueprints=0 and noncontiguous_series=0 and orphan_blueprints=0 then 'pass' else 'fail' end,'total_production_series',production_series,'covered_series',covered_series,'uncovered_series',uncovered_series,'duplicate_chapter_versions',duplicate_chapter_versions,'invalid_blueprints',invalid_blueprints,'noncontiguous_series',noncontiguous_series,'orphan_blueprints',orphan_blueprints,'rejected_historical_branches_excluded',true,'verified_at',now());
insert into public.taleforge_system_checks(check_key,category,status,score,details,checked_at) values('chapter_planning_integrity','architecture',case when result->>'status'='pass' then 'pass' else 'fail' end,case when result->>'status'='pass' then 100 else 0 end,result,now());
return result;
end; $$;
revoke all on function public.taleforge_verify_chapter_planning() from public,anon,authenticated;
grant execute on function public.taleforge_verify_chapter_planning() to service_role;
update public.taleforge_system_registry set status='active',authority_level=90,criticality='critical',health_check_prefix='chapter_planning_integrity',description='Governed chapter-level planning and blueprint integrity between Arc Planning and Generation.' where system_key='chapter_planning';
update public.chapter_blueprints set generation_status='planned',release_status='unreleased',updated_at=now() where id='c662b2a7-6b1d-4d04-afd9-3d4d1a55d954' and generation_status='rejected';