create table if not exists public.taleforge_generation_context_snapshots (
 id uuid primary key default gen_random_uuid(), series_id uuid not null references public.series(id) on delete cascade,
 chapter_blueprint_id uuid not null references public.chapter_blueprints(id) on delete cascade, chapter_number integer not null,
 context_version text not null default 'generation-context-v1', story_dna_version integer, story_identity_version integer,
 story_blueprint_version integer, arc_plan_version integer, chapter_blueprint_version integer, continuity_chapter_number integer,
 source_output_id uuid, context_hash text not null, payload jsonb not null default '{}'::jsonb, created_at timestamptz not null default now()
);
create index if not exists idx_taleforge_generation_context_series_chapter on public.taleforge_generation_context_snapshots(series_id,chapter_number,created_at desc);
create index if not exists idx_taleforge_generation_context_blueprint on public.taleforge_generation_context_snapshots(chapter_blueprint_id,created_at desc);
alter table public.taleforge_generation_context_snapshots enable row level security;

create or replace function public.taleforge_build_generation_context(p_blueprint_id uuid) returns jsonb
language plpgsql security definer set search_path=public as $$
declare b record; s record; dna record; ident record; sb record; arc record; cont record; profile record;
chars jsonb:='[]'::jsonb; rels jsonb:='[]'::jsonb; worlds jsonb:='[]'::jsonb; prev jsonb:='[]'::jsonb; ctx jsonb; snapshot_id uuid; hash text;
begin
select * into b from public.chapter_blueprints where id=p_blueprint_id; if not found then raise exception 'Chapter blueprint not found: %',p_blueprint_id; end if;
select * into s from public.series where id=b.series_id; if not found then raise exception 'Series not found for blueprint: %',p_blueprint_id; end if;
select * into dna from public.story_dna where series_id=b.series_id and status='active' order by version desc limit 1;
select * into ident from public.story_identity where series_id=b.series_id and status='active' order by version desc limit 1;
select * into sb from public.story_blueprints where series_id=b.series_id and generation_status not in ('rejected','archived') order by version desc,updated_at desc limit 1;
select * into arc from public.story_arc_plan where series_id=b.series_id and status='active' order by version desc limit 1;
select * into cont from public.story_continuity_state where series_id=b.series_id;
select * into profile from public.production_profiles where series_id=b.series_id and enabled=true order by updated_at desc limit 1;
select coalesce(jsonb_agg(jsonb_build_object('id',c.id,'name',c.name,'role',c.role,'aliases',c.aliases,'profile',c.profile,'goals',c.goals,'motivations',c.motivations,'traits',c.traits,'knowledge_state',c.knowledge_state,'secrets',c.secrets,'promises',c.promises,'unresolved_conflicts',c.unresolved_conflicts,'current_state',c.current_state,'first_appearance_chapter',c.first_appearance_chapter,'last_seen_chapter',c.last_seen_chapter,'status',c.status,'version',c.version) order by c.last_seen_chapter desc nulls last,c.name),'[]'::jsonb) into chars from public.story_characters c where c.series_id=b.series_id and c.status not in ('retired','deleted');
select coalesce(jsonb_agg(jsonb_build_object('id',r.id,'character_a_id',r.character_a_id,'character_b_id',r.character_b_id,'relationship_type',r.relationship_type,'status',r.status,'strength',r.strength,'details',r.details,'history',r.history,'last_changed_chapter',r.last_changed_chapter,'version',r.version) order by r.last_changed_chapter desc nulls last),'[]'::jsonb) into rels from public.character_relationships r where r.series_id=b.series_id and r.status not in ('retired','deleted');
select coalesce(jsonb_agg(jsonb_build_object('id',w.id,'name',w.name,'element_type',w.element_type,'description',w.description,'properties',w.properties,'rules',w.rules,'dependencies',w.dependencies,'known_by_characters',w.known_by_characters,'first_appearance_chapter',w.first_appearance_chapter,'last_referenced_chapter',w.last_referenced_chapter,'status',w.status,'version',w.version) order by w.last_referenced_chapter desc nulls last,w.name),'[]'::jsonb) into worlds from public.story_world_elements w where w.series_id=b.series_id and w.status not in ('retired','deleted');
select coalesce(jsonb_agg(jsonb_build_object('chapter_number',x.chapter_number,'title',x.title,'summary',x.summary,'recent_content',right(coalesce(x.content,''),3500)) order by x.chapter_number desc),'[]'::jsonb) into prev from (select chapter_number,title,summary,content from public.chapters where series_id=b.series_id and status='published' and chapter_number<b.chapter_number order by chapter_number desc limit 2) x;

ctx:=jsonb_build_object(
'context_version','generation-context-v1','assembled_at',now(),
'series',jsonb_build_object('id',s.id,'title',s.title,'subtitle',s.subtitle,'description',s.description,'mood',s.mood,'intensity',s.intensity,'age_rating',s.age_rating,'status',s.status),
'story_identity',case when ident.id is null then '{}'::jsonb else jsonb_build_object('id',ident.id,'version',ident.version,'display_title',ident.display_title,'display_subtitle',ident.display_subtitle,'one_line_hook',ident.one_line_hook,'identity_statement',ident.identity_statement,'genre_positioning',ident.genre_positioning,'tone_profile',ident.tone_profile,'audience_profile',ident.audience_profile,'discovery_keywords',ident.discovery_keywords,'seo_identity',ident.seo_identity,'source_dna_version',ident.source_dna_version) end,
'story_dna',case when dna.id is null then '{}'::jsonb else jsonb_build_object('version',dna.version,'core_premise',dna.core_premise,'central_theme',dna.central_theme,'reader_promise',dna.reader_promise,'narrative_voice',dna.narrative_voice,'protagonist_profiles',dna.protagonist_profiles,'relationship_map',dna.relationship_map,'world_rules',dna.world_rules,'story_constraints',dna.story_constraints,'mystery_threads',dna.mystery_threads,'payoff_targets',dna.payoff_targets,'forbidden_patterns',dna.forbidden_patterns,'genre_profile',dna.genre_profile) end,
'story_blueprint',case when sb.id is null then '{}'::jsonb else jsonb_build_object('id',sb.id,'version',sb.version,'premise',sb.premise,'hook',sb.hook,'theme',sb.theme,'tone',sb.tone,'plot_structure',sb.plot_structure,'conflict_type',sb.conflict_type,'protagonist_type',sb.protagonist_type,'narrative_style',sb.narrative_style,'pacing_style',sb.pacing_style,'ending_style',sb.ending_style,'world_concept',sb.world_concept,'world_rules',sb.world_rules,'character_plan',sb.character_plan,'world_plan',sb.world_plan,'arc_plan',sb.arc_plan,'chapter_plan',sb.chapter_plan,'ending_requirements',sb.ending_requirements,'required_payoffs',sb.required_payoffs,'required_end_state',sb.required_end_state) end,
'arc_plan',case when arc.id is null then '{}'::jsonb else jsonb_build_object('version',arc.version,'target_ending_chapter',arc.target_ending_chapter,'flexibility_min_chapter',arc.flexibility_min_chapter,'flexibility_max_chapter',arc.flexibility_max_chapter,'central_promise',arc.central_promise,'central_conflict',arc.central_conflict,'final_question',arc.final_question,'final_answer',arc.final_answer,'arcs',arc.arcs,'character_arcs',arc.character_arcs,'major_revelations',arc.major_revelations,'required_payoffs',arc.required_payoffs,'ending_requirements',arc.ending_requirements,'forbidden_padding',arc.forbidden_padding,'completion_definition',arc.completion_definition) end,
'chapter_blueprint',to_jsonb(b),
'production_profile',case when profile.profile_key is null then '{}'::jsonb else jsonb_build_object('profile_key',profile.profile_key,'genre',profile.genre,'narrative_rules',profile.narrative_rules,'world_rules',profile.world_rules,'character_rules',profile.character_rules,'pacing_rules',profile.pacing_rules,'hook_rules',profile.hook_rules) end,
'canonical_state',case when cont.series_id is null then '{}'::jsonb else jsonb_build_object('current_chapter_number',cont.current_chapter_number,'current_arc',cont.current_arc,'narrative_state',cont.narrative_state,'character_state',cont.character_state,'relationship_state',cont.relationship_state,'world_state',cont.world_state,'active_conflicts',cont.active_conflicts,'open_questions',cont.open_questions,'unresolved_clues',cont.unresolved_clues,'continuity_rules',cont.continuity_rules,'last_output_id',cont.last_output_id,'last_snapshot_id',cont.last_snapshot_id,'last_review_score',cont.last_review_score,'last_review_decision',cont.last_review_decision) end,
'characters',chars,'relationships',rels,'world_elements',worlds,'previous_published_chapters',prev,
'future_payoff_awareness',jsonb_build_object('dna_payoff_targets',coalesce(dna.payoff_targets,'[]'::jsonb),'arc_required_payoffs',coalesce(arc.required_payoffs,'[]'::jsonb),'story_blueprint_required_payoffs',coalesce(sb.required_payoffs,'[]'::jsonb),'ending_requirements',coalesce(arc.ending_requirements,'[]'::jsonb),'target_ending_chapter',arc.target_ending_chapter));
hash:=md5(ctx::text);
insert into public.taleforge_generation_context_snapshots(series_id,chapter_blueprint_id,chapter_number,story_dna_version,story_identity_version,story_blueprint_version,arc_plan_version,chapter_blueprint_version,continuity_chapter_number,context_hash,payload)
values(b.series_id,b.id,b.chapter_number,dna.version,ident.version,sb.version,arc.version,b.version,cont.current_chapter_number,hash,ctx) returning id into snapshot_id;
return jsonb_build_object('snapshot_id',snapshot_id,'context_hash',hash,'context',ctx);
end; $$;
revoke all on function public.taleforge_build_generation_context(uuid) from public,anon,authenticated;
grant execute on function public.taleforge_build_generation_context(uuid) to service_role;
